### ISSUE TITLE
Download Waveglow error

### ISSUE THREAD

**Issue by xiexukang** [ranchlai/mandarin-tts#12]
Traceback (most recent call last):
  File "/home/project/TTS/mandarin-tts/synthesize.py", line 126, in <module>
    waveglow = download_waveglow(device)
  File "/home/project/TTS/mandarin-tts/download_utils.py", line 164, in download_waveglow
    waveglow = torch.hub.load('./waveglow/DeepLearningExamples-torchhub/', 'nvidia_waveglow',source='local')
  File "/home/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/hub.py", line 345, in load
    repo_dir = _get_cache_or_reload(github, force_reload, verbose)
  File "/home/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/hub.py", line 121, in _get_cache_or_reload
    repo_owner, repo_name, branch = _parse_repo_info(github)
  File "/homeg/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/hub.py", line 111, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)

**Comment by ranchlai** [comment]
please use new branch: mtts. 
Master branch is outdated. 
Torchhub is unstable and in new branch mtts I have removed torchhub.
