### ISSUE TITLE
关于hparams包

### ISSUE THREAD

**Issue by lgf821793883** [ranchlai/mandarin-tts#9]
Traceback (most recent call last):
  File "synthesize.py", line 7, in <module>
    from fastspeech2 import FastSpeech2
  File "F:\project\mandarin-tts-master\fastspeech2.py", line 5, in <module>
    from transformer.Models import Encoder, Decoder
  File "F:\project\mandarin-tts-master\transformer\__init__.py", line 5, in <module>
    import transformer.Models
  File "F:\project\mandarin-tts-master\transformer\Models.py", line 33, in <module>
    class Encoder(nn.Module):
  File "F:\project\mandarin-tts-master\transformer\Models.py", line 39, in Encoder
    len_max_seq=hp.max_seq_len,
AttributeError: module 'hparams' has no attribute 'max_seq_len'

请问这个问题怎么解决，版本也试过好几个了，不太行。

**Comment by ranchlai** [comment]
后续代码会重构，可以保持关注。 我打算建一个语音的纯技术交流群~~统一回答问题

**Comment by lgf821793883** [comment]
好 ，群号发一下
